loki/urls.py
from django.contrib import admin

from django.urls import path
from django.urls import include

from .views import index
from .views import login
from .views import register
from .views import logout

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('legrappe/admin/admin', admin.site.urls),
    path('', index, name='index'),

    path('login/', login, name='login'),
    path('register', register, name='register'),
    path('logout', logout, name='logout'),

    path('wallets/', include('wallets.urls')),
    path('tokens/', include('tokens.urls')),
    path('retrieves/', include('retrieves.urls')),
    path('transactions/', include('transactions.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tokens/urls.py
from django.urls import path

from . import views

app_name = 'tokens'

urlpatterns = [
    path('', views.ListTokenView.as_view(), name='list'),
    path('<int:pk>', views.TokenDetailView.as_view(), name='detail'),
    path('<int:pk>/abi', views.abi, name='abi'),
    path('create', views.CreateTokenForm.as_view(), name='create'),
    path('update/<int:pk>', views.UpdateTokenView.as_view(), name='update'),
    path('delete/<int:pk>', views.TokenDeleteView.as_view(), name='delete'),
]

tokens/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.db.models.signals import post_save

from Web3API.abis import abi
from Web3API.abis import total_supply

class Token(models.Model):
    address = models.CharField(max_length=255, null=False, blank=False)
    name = models.CharField(max_length=255, null=False, blank=False)
    symbol = models.CharField(max_length=50, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True, null=False, blank=False)
    abi = models.TextField(null=True, blank=True)
    image = models.CharField(max_length=500, blank=True, null=True, default='')
    supply = models.BigIntegerField(null=True, blank=True)
    total = models.BigIntegerField(null=False, blank=False)
    coingecko_id = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return f"{self.symbol}"


    def set_abi(self):
        if self.abi:
            return self.abi

        response = abi(self)
        if response:
            self.abi = str(response)
            self.save()

        return self.abi

    def set_total_supply(self):
        if self.supply:
            return self.supply
        
        self.supply = total_supply(self)
        self.save()


def set_abi(sender, instance, *args, **kwargs):
    instance.set_abi()


def set_total_supply(sender, instance, created, raw, using, update_fields, *args, **kwargs):
    instance.set_total_supply()


pre_save.connect(set_abi, sender=Token)
# post_save.connect(set_total_supply, sender=Token)

tokens/forms.py
from django.forms import ModelForm

from .models import Token

class TokenForm(ModelForm):
    class Meta:
        model = Token
        fields = ['address', 'name', 'symbol', 'image', 'active', 'total', 'coingecko_id']
        labels = {'address': 'Dirección', 'name': 'Nombre', 'symbol': 'Símbolo', 'image': 'Imagen', 'active': 'Activo'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['address'].widget.attrs.update({
            'class': 'appearance-none block w-full py-3 px-4 leading-tight text-gray-700 bg-gray-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none',
            'id': 'address',
            'placeholder': 'Address'
        })

        self.fields['name'].widget.attrs.update({
            'class': 'appearance-none block w-full py-3 px-4 leading-tight text-gray-700 bg-gray-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none',
            'id': 'name',
            'placeholder': 'Nombre'
        })

        self.fields['symbol'].widget.attrs.update({
            'class': 'appearance-none block w-full py-3 px-4 leading-tight text-gray-700 bg-gray-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none',
            'id': 'symbol',
            'placeholder': 'Símbolo'
        })


        self.fields['image'].widget.attrs.update({
            'class': 'appearance-none block w-full py-3 px-4 leading-tight text-gray-700 bg-gray-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none',
            'id': 'image',
            'placeholder': 'Imagen'
        })

        self.fields['total'].widget.attrs.update({
            'class': 'appearance-none block w-full py-3 px-4 leading-tight text-gray-700 bg-gray-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none',
            'id': 'total',
            'placeholder': 'Cantidad por la cual se hará la división'
        })

        self.fields['coingecko_id'].widget.attrs.update({
            'class': 'appearance-none block w-full py-3 px-4 leading-tight text-gray-700 bg-gray-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none',
            'id': 'tocoingecko_idtal',
            'placeholder': 'Id de CoinGecko'
        })

        self.fields['active'].label = "Estatus Activo"

tokens/views.py
from django.shortcuts import render
from django.shortcuts import reverse
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404

from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView

from django.utils.decorators import method_decorator

from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from tokens.models import Token

from .forms import TokenForm

from users.decorators import admin_validator

from django.urls import reverse_lazy

class TokenDeleteView(LoginRequiredMixin, DeleteView):
    model = Token
    success_url = reverse_lazy('tokens:list')

    @method_decorator(admin_validator)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ListTokenView(LoginRequiredMixin, ListView):
    model = Token
    login_url = '/login/'
    template_name = 'tokens/list.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


    def get_queryset(self):
        return Token.objects.filter().order_by('-id')


    @method_decorator(admin_validator)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class CreateTokenForm(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Token
    template_name = 'tokens/create.html'
    login_url = '/login/'
    form_class = TokenForm
    success_message = 'Token registrado existosamente'

    def get_success_url(self):
        return reverse('tokens:list')


    @method_decorator(admin_validator)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class UpdateTokenView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Token
    login_url = '/login/'
    template_name = 'tokens/update.html'
    form_class = TokenForm
    success_message = 'Token actualizado existosamente'


    def get_success_url(self):
        return reverse('tokens:list')


    @method_decorator(admin_validator)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class TokenDetailView(LoginRequiredMixin, SuccessMessageMixin, DetailView):
    model = Token
    login_url = '/login/'
    template_name = 'tokens/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


def abi(request, pk):
    token = get_object_or_404(Token, pk=pk)
    
    token.set_abi()
    token.set_total_supply()

    return redirect('tokens:list')

tokens/templates/tokens/create.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container mx-auto px-4"> 
    
  {% include 'base/snippets/navbar.html' %}

  <section class="py-12 px-4 text-center">
    <div class="w-full max-w-2xl mx-auto">
      <h2 class="text-5xl mt-2 mb-6 leading-tight font-semibold font-heading">Nuevo Token</h2>
    </div>
  </section>

{% include 'tokens/snippets/form.html' with message='Crear' %}

{% endblock %}

tokens/templates/tokens/detail.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<div class="container mx-auto px-4"> 
    
  {% include 'base/snippets/navbar.html' %}

  <section class="mt-2">
    <div class="py-4 px-8 bg-white shadow-lg rounded-lg my-20">
      <div class="flex justify-center md:justify-end -mt-16">
        <img class="object-cover " src="{% static 'image/coins/'%}{{token.image}}.webp">
      </div>

      <div>
        <h2 class="text-gray-800 text-3xl font-semibold">{{ object.symbol }}</h2>
      </div>

      <div class="rows mt-2">
        <div class="row align-items-center">

          <div class="flex flex-wrap -mx-4 mt-4">
            <div class="w-full md:w-1/4 px-4 mb-2">
              Name
            </div>
            <div class="w-full md:w-3/4 px-4 mb-4 md:mb-0">
               {{ object.name }}
            </div>
          </div>
          <hr class="hr-space">
          
          <div class="flex flex-wrap -mx-4 mt-4">
            <div class="w-full md:w-1/4 px-4 mb-2">
              Address
            </div>
            <div class="w-full md:w-3/4 px-4 mb-4 md:mb-0">
               {{ object.address }} 
            </div>
          </div>
          <hr class="hr-space">

          <div class="flex flex-wrap -mx-4 mt-4">
            <div class="w-full md:w-1/4 px-4 mb-2">
              Total Supply
            </div>
            <div class="w-full md:w-3/4 px-4 mb-4 md:mb-0">
               {{ object.total_supply }}
            </div>
          </div>
          <hr class="hr-space">

          <div class="flex flex-wrap -mx-4 mt-4">
            <div class="w-full md:w-1/4 px-4 mb-2">
              ABI
            </div>
            <div class="w-full md:w-3/4 px-4 mb-4 md:mb-0">
               {{ object.abi|truncatechars:50 }}
            </div>
          </div>
      </div>

      <div class="flex justify-end mt-4">
        <a class="text-right inline-block py-3 px-6 ml-2 leading-none text-white bg-yellow-600 hover:bg-yellow-700 font-semibold rounded shadow" href="{% url 'tokens:update' object.pk %}">Editar</a>
        <a class="text-right inline-block py-3 px-6 ml-2 leading-none text-white bg-indigo-600 hover:bg-indigo-700 font-semibold rounded shadow" href="{% url 'tokens:abi' object.pk %}">Set ABY & >Supply</a>
      </div>
    </div>

  </section>

{% endblock %}

tokens/templates/tokens/list.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<div class="container mx-auto px-4"> 
    
  {% include 'base/snippets/navbar.html' %}

  <section class="py-12">
    <div class="w-full mx-auto">
      
      <div class="flex flex-wrap -mx-4 -mb-4 md:mb-0">
        <div class="w-full md:w-1/2 px-4 mb-4 md:mb-0">
            <h2 class="text-3xl mb-2 font-semibold font-heading font-semibold text-left">Listado de tokens {{ token.alias }}</h2>
        </div>
        <div class="w-full md:w-1/2 px-4 mb-4 md:mb-0 text-right">
            <a class="inline-block py-3 px-6 leading-none text-white bg-purple-600 hover:bg-purple-700 font-semibold rounded shadow" href="{% url 'tokens:create' %}">Nuevo token</a>
        </div>
    </div>
    <br>
    <section>
        <table class="w-full table-auto">
            <thead>
            <tr>
                <th class="border-t px-2 py-2" scope="col"></th>
                <th class="border-t px-2 py-2" scope="col">Address</th>
                <th class="border-t px-2 py-2" scope="col">Name</th>
                <th class="border-t px-2 py-2" scope="col">Symbol</th>
                <th class="border-t px-2 py-2" scope="col">Active</th>
                <th class="border-t px-2 py-2" scope="col"></th>
            </thead>
            <tbody>
                {% for token in object_list %}
                    <tr>
                        <td class="text-center border-t px-2 py-2">
                            <img src="{% static 'image/coins/'%}{{token.image}}.webp" width="30" height="30">
                        </td>
                        <td class="text-center border-t px-2 py-2">{{ token.address }} </td>
                        <td class="text-center border-t px-2 py-2">{{ token.name }}</td>
                        <td class="text-center border-t px-2 py-2">{{ token.symbol }}</td>
                        <td class="text-center border-t px-2 py-2">
                            <strong class="{% if token.active %} text-green-600 {% else %} text-red-600 {% endif %}"> {{ token.active }} </strong>
                        </td>
                        <td class="text-center border-t px-2 py-2">
                            <div >
                                <a class="inline-block py-3 px-6 leading-none text-white bg-purple-600 hover:bg-purple-700 font-semibold rounded shadow" href="{% url 'tokens:update' token.id  %}">Editar</a>
                                <a class="inline-block py-3 px-6 leading-none text-white bg-green-600 hover:bg-green-700 font-semibold rounded shadow" href="{% url 'tokens:detail' token.id  %}">Ver</a>
                                <div class="inline-block">
                                    <form action="{% url 'tokens:delete' token.id %}" method="POST">
                                        {% csrf_token %} 
                                        <input type="submit" value="Eliminar" class="py-3 px-6 leading-none text-white bg-red-600 hover:bg-red-700 font-semibold rounded shadow">
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>

  </section>

{% endblock %}

tokens/templates/tokens/update.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container mx-auto px-4"> 
    
  {% include 'base/snippets/navbar.html' %}

  <section class="py-12 px-4 text-center">
    <div class="w-full max-w-2xl mx-auto">
      <h2 class="text-5xl mt-2 mb-6 leading-tight font-semibold font-heading">Editar Token</h2>
    </div>
  </section>

{% include 'tokens/snippets/form.html' with message='Actualizar' %}

{% endblock %}