loki/urls.py
from django.contrib import admin

from django.urls import path
from django.urls import include

from .views import index
from .views import login
from .views import register
from .views import logout

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('legrappe/admin/admin', admin.site.urls),
    path('', index, name='index'),

    path('login/', login, name='login'),
    path('register', register, name='register'),
    path('logout', logout, name='logout'),

    path('wallets/', include('wallets.urls')),
    path('tokens/', include('tokens.urls')),
    path('retrieves/', include('retrieves.urls')),
    path('transactions/', include('transactions.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wallets/urls.py
from django.urls import path

from . import views

app_name = 'wallets'

urlpatterns = [
    path('admin', views.admin, name='admin'),
    
    path('balance', views.balance, name='balance'),
    path('dashboard', views.dashboard, name='dashboard'),
    
    path('create', views.CreateWalletView.as_view(), name='create'),
    path('delete/<int:pk>', views.WalletDeleteView.as_view(), name='delete'),
    path('update/<int:pk>', views.WalletUpdateView.as_view(), name='update'),
]

balances/models.py
from django.db import models

# Create your models here.

wallets/models.py
from django.db import models
from users.models import User
from tokens.models import Token

from django.core.exceptions import ValidationError

from django.db.models.signals import pre_save
from django.db.models.signals import post_save

class Wallet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hexadecimal = models.CharField(max_length=254, null=False, blank=False) # Hexadecimal is the field without prefix 0x
    address = models.CharField(max_length=254, null=False, blank=False)
    alias = models.CharField(max_length=100, null=False, blank=False, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    tokens = models.ManyToManyField(Token, through='wallet_tokens.WalletTokens')
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.hexadecimal


def hexadecimal_format(address):
    return address.lower()[2:] # Remove prefix


def hexadecimal_address_exists(hexadecimal):
    hexadecimal = hexadecimal.lower()
    return Wallet.objects.filter(hexadecimal=hexadecimal).exclude(hexadecimal=hexadecimal).exists()

"""
def validate_if_address_exists(sender, instance, *args, **kwargs):
    if address_exists(instance.address):
        raise ValidationError('La dirección ya se encuentra registrada!')
"""

def set_wallet_format(sender, instance, *args, **kwargs):
    instance.hexadecimal = hexadecimal_format(instance.address)


def check_default(sender, instance, created, *args, **kwargs):
    if instance.default == False and Wallet.objects.filter(user=instance.user).filter(default=True).exists() == False:
        instance.default = True
        instance.save()

def update_default(sender, instance, created, *args, **kwargs):
    if instance.default:
        
        for wallet in Wallet.objects.filter(user=instance.user).exclude(pk=instance.pk):
            wallet.default = False
            wallet.save()


pre_save.connect(set_wallet_format, sender=Wallet)

post_save.connect(check_default, sender=Wallet)
post_save.connect(update_default, sender=Wallet)

wallets/forms.py
import re

from django.forms import Select

from django.forms import ModelForm
from django.forms import CheckboxSelectMultiple
from django.forms import ModelMultipleChoiceField

from django.core.exceptions import ValidationError

from .models import Wallet
from .models import hexadecimal_format
from .models import hexadecimal_address_exists

from tokens.models import Token

class WalletForm(ModelForm):

    def clean_address(self):
        address = self.cleaned_data['address']
        
        if self.is_hexadecimal(address) is None:
            raise ValidationError("Dirección no valida.")

        if hexadecimal_address_exists(hexadecimal_format(address)):
            raise ValidationError("La dirección ya se encuentra registrada.")

        return address



    def is_hexadecimal(self, data):
        return re.fullmatch(r"^(0x|0X)?[a-fA-F0-9]+$", data or "") # BSC validate addresses


class WalletCreateForm(WalletForm):
    class Meta:
        model = Wallet
        fields = ['address', 'alias', 'tokens', 'default']
        labels = {'address': 'Dirección', 'alias': 'Alías', 'tokens': 'Tokens', 'default': 'default'}


    tokens = ModelMultipleChoiceField(
        queryset=None,
        widget=CheckboxSelectMultiple
    )


    def __init__(self, disabled=False, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['address'].widget.attrs.update({
            'class': 'block w-full py-3 px-4 leading-tight text-gray-700 bg-gray-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none',
            'id': 'address',
            'placeholder': 'Address'
        })

        self.fields['address'].disabled = disabled

        self.fields['alias'].widget.attrs.update({
            'class': 'block w-full py-3 px-4 leading-tight text-gray-700 bg-gray-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none',
            'id': 'alias',
            'placeholder': 'Alías'
        })

        self.fields['tokens'].queryset = Token.objects.filter(active=True)
        self.fields['tokens'].widget.attrs.update(
            { 'class':'ml-1' }
        )

        self.fields['default'].widget.attrs.update(
            { 'class':'mt-1' }
        )
        self.fields['default'].label = "Billetera principal"


class WalletUpdateForm(WalletForm):
    class Meta:
        model = Wallet
        fields = ['alias', 'tokens', 'default' ]
        labels = {'alias': 'Alías', 'tokens': 'Tokens', 'default': 'Billetera principal'}

    tokens = ModelMultipleChoiceField(
        queryset=None,
        widget=CheckboxSelectMultiple
    )

    def __init__(self, disabled=False, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['alias'].widget.attrs.update({
            'class': 'block w-full py-3 px-4 leading-tight text-gray-700 bg-gray-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none',
            'id': 'alias',
            'placeholder': 'Alías'
        })

        self.fields['tokens'].queryset = Token.objects.filter(active=True)
        self.fields['tokens'].widget.attrs.update(
            { 'class':'ml-1' }
        )

        self.fields['default'].label = "Billetera principal"

    

balances/views.py
from django.shortcuts import render

# Create your views here.

wallets/views.py
from django.urls import reverse_lazy


from django.shortcuts import reverse
from django.shortcuts import redirect
from django.shortcuts import render

from django.contrib import messages

from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView

from django.http import HttpResponseRedirect

from django.core.serializers import serialize

from .models import Wallet

from .forms import WalletCreateForm
from .forms import WalletUpdateForm

from tokens.models import Token
from transactions.models import Transaction
from wallet_tokens.models import WalletTokens

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from Web3API.wallets import total_balance_of

@login_required(login_url='/login')
def dashboard(request):
    if Wallet.objects.filter(user=request.user).exists():

        wallet = Wallet.objects.filter(user=request.user).filter(default=True).first()
        
        return render(request, 'wallets/dashboard.html', {
            'wallet': wallet,

        })

    else:
        return redirect('wallets:admin')


@login_required(login_url='/login')
def balance(request):
    return render(request, 'wallets/balance.html', {
    })


@login_required(login_url='/login')
def admin(request):
    
    if Wallet.objects.filter(user_id=request.user.id).exists():
        return redirect('wallets:dashboard')

    return render(request, 'wallets/admin.html', {})


class CreateWalletView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Wallet
    template_name = 'wallets/create.html'
    login_url = '/login/'
    form_class = WalletCreateForm
    success_message = "Wallet eactualizada exitosamente"

    def get_success_url(self):
        return reverse('wallets:dashboard')


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['form'] = WalletCreateForm(
            initial={
                'default': not Wallet.objects.filter(user=self.request.user).exists()
            }
        )
        
        return context

    def post(self, request, *args, **kwargs):
        return super(CreateWalletView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class WalletDeleteView(DeleteView):
    model = Wallet
    success_url = reverse_lazy('wallets:list')
    

class WalletUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Wallet
    template_name = 'wallets/update.html'
    login_url = '/login/'
    form_class = WalletUpdateForm
    success_message = "Wallet actualizada exitosamente"

    def get_success_url(self):
        return reverse('wallets:dashboard')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tokens'] = [ wt['token_id'] for wt in WalletTokens.objects.filter(wallet_id=self.get_object().id).values('token_id')]
        return context

wallets/templates/wallets/admin.html
{% extends 'base/base.html' %}

{% block content %}

<div class="container mx-auto px-4"> 
    {% include 'base/snippets/navbar.html' %}

    <section class="py-12 px-4 text-center">
        <div class="w-full max-w-2xl mx-auto">
          <div class="mb-10">
            <h2 class="text-5xl mb-8 leading-tight font-semibold font-heading">Áun no cuentas con una billetera cripto registrada.</h2>
            <p class="text-gray-400 leading-relaxed">Antes de registrar tu wallet te damos las siguientes recomendaciones:</p>
            <br>
            <p class="text-gray-400 leading-relaxed">- Nunca compartas tu llaves privadas con nadie</p>
            <p class="text-gray-400 leading-relaxed">- Una muy buena idea es siempre crear nuevas billeteras para diferentes propositos.</p>
            <p class="text-gray-400 leading-relaxed">- Las notificaciones te serán enviadas vía correo electrónico, así que asegura tu email sea el correcto.</p>
            <p class="text-gray-400 leading-relaxed">
                <strong>
                    - Registra billeteras validas para la Binance Smart Chain (BEP20)
                </strong>
            </p>
          </div>
          
            <div class="flex flex-wrap">
              <div class="w-full">
                <a class="inline-block w-full py-4 px-8 mt-6 leading-none text-white bg-indigo-600 hover:bg-indigo-700 font-semibold rounded shadow" href="{% url 'wallets:create' %}">Registrar billetera</a>
              </div>
            </div>
        </div>
      </section>

{% endblock %}

wallets/templates/wallets/balance.html
{% extends 'base/base.html' %}

{% block content %}
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.js"></script>

<div id="app">  
    <div class="container mx-auto px-4"> 
        {% include 'base/snippets/navbar.html' %}
        
            <section class="py-12 px-4 text-center">
                {% verbatim %}
                    <div class="mb-6">
                        <label class="block text-gray-700 text-sm font-bold mb-2 text-left" for="">Mis billeteras</label>
                        <div class="relative">
                        <select @change="onChange($event)" class="appearance-none block w-full py-3 px-4 leading-tight text-gray-700 bg-gray-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none" name="field-name">
                            <option v-for="wallet in wallets" v-bind:value="wallet.id">
                                {{ wallet.alias }} - {{ wallet.hexadecimal }}
                            </option>
                        </select>
                        <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                            <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                            <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"></path>
                            </svg>
                        </div>
                        </div>
                    </div>
                {% endverbatim %}

                <div class="flex texte-center flex-wrap -mx-4 -mb-4 md:mb-0">
                    <div class="w-full md:w-1/3 px-4 mb-4 md:mb-0"></div>
                    <div class="w-full md:w-1/3 px-4 mb-4 md:mb-0">
                        {% verbatim %}
                            <a class="inline-block py-3 px-6 leading-none text-white bg-yellow-600 hover:bg-yellow-700 font-semibold rounded shadow" :href="'/wallets/update/' + currentWalletId" id="update-link">Editar billetera</a>
                        {% endverbatim %}
                        <a class="inline-block py-3 px-6 leading-none text-white bg-indigo-600 hover:bg-indigo-700 font-semibold rounded shadow" href="{% url 'wallets:create' %}">Nueva billetera</a>
                    </div>
                    <div class="w-full md:w-1/3 px-4 mb-4 md:mb-0"></div>
                </div>
            </section>

            <section>
                <strong>{{ total }}</strong>
            </section>

            <hr>
            <br>
            
            <section class="px-4">
                <a class="inline-block py-3 px-6 leading-none text-white bg-purple-600 hover:bg-purple-700 font-semibold rounded shadow" href="{% url 'wallets:dashboard' %}">Transacciones</a>
                <a class="inline-block py-3 px-6 leading-none text-white bg-pink-600 hover:bg-pink-700 font-semibold rounded shadow" href="{% url 'wallets:balance' %}">Balances</a>
            </section>

            {% verbatim %}
                <section class="px-4">

                    <table class="w-6/12 mt-4">
                        <thead>
                        <tr>
                            <th class="border-t px-2 py-2" scope="col"></th>
                            <th class="border-t px-2 py-2" scope="col">En cartera</th>
                            <th class="border-t px-2 py-2" scope="col">Precio actual</th>
                            <th class="border-t px-2 py-2" scope="col">Total USD</th>
                        </thead>
                        <tbody>
                            <tr v-for="token in tokens">
                                <td class="text-center border-t px-2 py-2 mr-4">
                                    <img class="inline-block"  v-bind:src="'/static/image/coins/' + token.image + '.webp'" width="30" height="30"/> 
                                    <strong class="inline-block ml-4">
                                        {{ token.symbol }}
                                    </strong>
                                </td>
                                <td class="text-center border-t px-2 py-2">{{ token.balance  }} </td>
                                <td class="text-center border-t px-2 py-2">{{ token.price }} </td>
                                <td class="text-center border-t px-2 py-2"> {{ token.total }} </td>
                            </tr>
                        </tbody>
                    </table>
                </section>
            {% endverbatim %}
        
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    
    var app = new Vue({
        el: '#app',
        data: {
            currentWalletId: 0,
            wallets: [],
            tokens: [],
        },

        created() {
            axios.get('/retrieves/wallets').then(response => {
                this.wallets = response.data.wallets;
                this.currentWalletId = this.wallets[0].id;

                this.loadBalance(this.currentWalletId);
            });
        },

        methods: {
            onChange(event) {
                this.reset();
                this.loadBalance(event.target.value)
            },

            loadBalance(walletId) {
                axios.get('/retrieves/balance/' + walletId).then(response => {
                    this.tokens = response.data.tokens;
                });
            },

            reset() {
                this.tokens = [];
            }
        }
    })
</script>
{% endblock %}

wallets/templates/wallets/create.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container mx-auto px-4"> 
    
  {% include 'base/snippets/navbar.html' %}

  <section class="py-12 px-4 text-center">
    <div class="w-full max-w-2xl mx-auto">
      
      <h2 class="text-5xl mt-2 mb-6 leading-tight font-semibold font-heading">Nueva Wallet</h2>
      <span class="text-sm font-semibold">Registra direcciones para la Binance Smart Chain (BEP20)</span>
      <a class="text-indigo-600 hover:underline" href="https://academy.binance.com/en/glossary/bep-20" target="_blank">Conoce más</a>
    </div>
  </section>

{% include 'wallets/snippets/form.html' with message='Registrar billetera' %}


{% endblock %}

wallets/templates/wallets/dashboard.html
{% extends 'base/base.html' %}

{% block content %}
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.js"></script>

<div id="app">  
    <div class="container mx-auto px-4"> 
        {% include 'base/snippets/navbar.html' %}
        
            <section class="py-12 px-4 text-center">
                {% verbatim %}
                    <div class="mb-6">
                        <label class="block text-gray-700 text-sm font-bold mb-2 text-left" for="">Mis billeteras</label>
                        <div class="relative">
                        <select @change="onChange($event)" class="appearance-none block w-full py-3 px-4 leading-tight text-gray-700 bg-gray-50 focus:bg-white border border-gray-200 focus:border-gray-500 rounded focus:outline-none" name="field-name">
                            <option v-for="wallet in wallets" v-bind:value="wallet.id">
                                {{ wallet.alias }} - {{ wallet.hexadecimal }}
                            </option>
                        </select>
                        <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                            <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                            <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"></path>
                            </svg>
                        </div>
                        </div>
                    </div>
                {% endverbatim %}

                <div class="flex texte-center flex-wrap -mx-4 -mb-4 md:mb-0">
                    <div class="w-full md:w-1/3 px-4 mb-4 md:mb-0"></div>
                    <div class="w-full md:w-1/3 px-4 mb-4 md:mb-0">
                        {% verbatim %}
                            <a class="inline-block py-3 px-6 leading-none text-white bg-yellow-600 hover:bg-yellow-700 font-semibold rounded shadow" :href="'/wallets/update/' + currentWalletId" id="update-link">Editar billetera</a>
                        {% endverbatim %}
                        <a class="inline-block py-3 px-6 leading-none text-white bg-indigo-600 hover:bg-indigo-700 font-semibold rounded shadow" href="{% url 'wallets:create' %}">Nueva billetera</a>
                    </div>
                    <div class="w-full md:w-1/3 px-4 mb-4 md:mb-0"></div>
                </div>
            </section>

            <section>
                <strong>{{ total }}</strong>
            </section>

            <hr>
            <br>
            
            <section class="px-4">
                <a class="inline-block py-3 px-6 leading-none text-white bg-purple-600 hover:bg-purple-700 font-semibold rounded shadow" href="{% url 'wallets:dashboard' %}">Transacciones</a>
                <a class="inline-block py-3 px-6 leading-none text-white bg-pink-600 hover:bg-pink-700 font-semibold rounded shadow" href="{% url 'wallets:balance' %}">Balances</a>
            </section>

            {% verbatim %}
                <section class="px-4">
                    <p class="mb-4 mt-2">Depósitos de los últimos 30 días.</p>
                    <div class="flex flex-wrap -mx-4 mb-8">
                        <div class="w-full lg:w-1/3 px-4 mb-6 lg:mb-0">
                        <div class="h-full">
                            <div class="text-center p-4 mb-2 bg-blue-500 text-white rounded">
                            <h3 class="text-3xl leading-tight font-semibold font-heading font-semibold">{{ total }}</h3>
                            <span class="leading-none">Total de transacciones</span>
                            </div>
                        </div>
                        </div>
                        <div class="w-full lg:w-1/3 px-4 mb-6 lg:mb-0">
                        <div class="h-full">
                            <div class="text-center p-4 mb-2 bg-green-500 text-white rounded">
                            <h3 class="text-3xl leading-tight font-semibold font-heading font-semibold">{{ deposits }}</h3>
                            <span class="leading-none">Depositos</span>
                            </div>
                        </div>
                        </div>
                        <div class="w-full lg:w-1/3 px-4 mb-6 lg:mb-0">
                        <div class="h-full">
                            <div class="text-center p-4 mb-2 bg-gray-800 text-white rounded">
                            <h3 class="text-3xl leading-tight font-semibold font-heading font-semibold">$ {{ balance }}</h3>
                            <span class="leading-none">Balance total (USD)</span>
                            </div>
                        </div>
                        </div>
                    </div>
                    <table class="w-full table-auto">
                        <thead>
                        <tr>
                            <th class="border-t px-2 py-2" scope="col">N° Bloque</th>
                            <th class="border-t px-2 py-2" scope="col">Dirección de envío</th>
                            <th class="border-t px-2 py-2" scope="col">Contrato</th>
                            <th class="border-t px-2 py-2" scope="col">Cantidad</th>
                            <th class="border-t px-2 py-2" scope="col">Estatus</th>
                            <th class="text-center border-t px-2 py-2" scope="col">Fecha de registro</th>
                            <th class="text-center border-t px-2 py-2" scope="col"></th></tr>
                        </thead>
                        <tbody>
                            <tr v-for="transaction in transactions">
                                <td class="text-center border-t px-2 py-2">{{ transaction.block }} </td>
                                <td class="text-center border-t px-2 py-2">{{ transaction.sender }}</td>
                                <td class="text-center border-t px-2 py-2">
                                    <img class="inline-block"  v-bind:src="'/static/image/coins/' + transaction.token__image + '.webp'" width="30" height="30"/> 
                                    <p class="inline-block ml-4">
                                        {{ transaction.token__symbol }}
                                    </p>
                                </td>
                                <td class="text-center border-t px-2 py-2">{{ transaction.amount }}</td>
                                <td class="text-center border-t px-2 py-2">
                                    <span class="inline-block text-sm py-1 px-3 rounded-full text-white bg-green-500">
                                        {{ transaction.status }}
                                    </span>
                                </td>
                                <td class="text-center border-t px-2 py-2">{{ transaction.created_at }}</td>
                                <td class="text-center border-t px-2 py-2">
                                    <a class="text-indigo-600 hover:underline" v-bind:href="'/transactions/detail/' + transaction.id ">Ver más</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <a v-if="count > 10" class="text-indigo-600 hover:underline" href="#">Ver más</a>
                </section>
            {% endverbatim %}
            <br>
            <hr>
        
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    
    var app = new Vue({
        el: '#app',
        data: {
            currentWalletId: 0,
            wallets: [],
            transactions: [],
            total: 0,
            deposits:0,
            balance:0,
            count:0
        },

        created() {
            axios.get('/retrieves/wallets').then(response => {
                this.wallets = response.data.wallets;
                this.currentWalletId = this.wallets[0].id;

                this.loadDashboard(this.currentWalletId);
            });
        },

        methods: {
            onChange(event) {
                this.reset();
                this.loadDashboard(event.target.value)
            },

            loadDashboard(walletId) {
                axios.get('/retrieves/dashboard/' + walletId).then(response => {
                    this.total = response.data.total;
                    this.count = response.data.count;

                    this.balance = response.data.balance;
                    this.deposits = response.data.deposits;

                    this.transactions = response.data.transactions;
                    this.currentWalletId = walletId;

                });
            },

            reset() {
                this.transactions = [];
                this.total = 0;
                this.deposits = 0;
                this.balance = 0,
                this.count = 0
            }
        }
    })
</script>
{% endblock %}

wallets/templates/wallets/update.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container mx-auto px-4"> 
    
  {% include 'base/snippets/navbar.html' %}

  <section class="py-12 px-4 text-center">
    <div class="w-full max-w-2xl mx-auto">
      
      <h2 class="text-5xl mt-2 mb-6 leading-tight font-semibold font-heading">Editar Wallet</h2>
      <span class="text-sm font-semibold">{{ object.alias }} - {{ object.address }}</span>
    </div>
  </section>
  
{% include 'wallets/snippets/form.html' with message='Actualizar billetera' %}

{% endblock %}